// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentTesting.Models;

namespace StudentTesting.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20220715070610_migr5")]
    partial class migr5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentTesting.Models.MarksTable", b =>
                {
                    b.Property<int>("MarksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Subject1")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Subject2")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Subject3")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Subject4")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Subject5")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Subject6")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("MarksId");

                    b.HasIndex("StudentId");

                    b.ToTable("markstables");
                });

            modelBuilder.Entity("StudentTesting.Models.Studenttbl", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Mobile_No")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reg_no")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StudentId");

                    b.ToTable("studenttbls");
                });

            modelBuilder.Entity("StudentTesting.Models.Teachertbl", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultyId");

                    b.ToTable("teachertbls");
                });

            modelBuilder.Entity("StudentTesting.Models.MarksTable", b =>
                {
                    b.HasOne("StudentTesting.Models.Studenttbl", "studenttbl")
                        .WithMany("markstable")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("studenttbl");
                });

            modelBuilder.Entity("StudentTesting.Models.Studenttbl", b =>
                {
                    b.Navigation("markstable");
                });
#pragma warning restore 612, 618
        }
    }
}
